FROM registry.access.redhat.com/ubi9/ubi-minimal AS BUILD

FROM registry.access.redhat.com/ubi9/ubi-micro

COPY --from=BUILD \
   "/usr/lib64/libgcc_s.so.1" \
   "/usr/lib64/libstdc++.so.6" \
   "/usr/lib64/libz.so.1" \
   /usr/lib64/

WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/*-runner /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
